### ISSUE TITLE
Can't run locally

### ISSUE THREAD

**Issue by MichaelWehar** [erasche/woordschaap#1]
Hi there!

I tried to run your app locally in my web browser, but couldn't seem to get it to work.

When I went to inspect, I noticed a few error messages:

- Uncaught ReferenceError: module is not defined at index.js:274
- Fetch API cannot load wordlists/nl.5000.json URL scheme must be "http" or "https" for CORS request. main @ select.js:591
- Uncaught (in promise) TypeError: Failed to fetch at main (select.js:591) at select.js:619

I'm excited to see what it looks like!

Hope that you have a nice day!

Mike

**Comment by hexylena** [comment]
Hi @MichaelWehar, it's available on https://erasche.github.io/woordschaap/ if you want to see it there, so everything should be here that is needed.

I've hardcoded a number of things since this was a quick personal project for family use, so beware that.

> Uncaught ReferenceError: module is not defined at index.js:274

that one happens always, in one of the libraries I've loaded, but doesn't seem to affect functionality.

> Fetch API cannot load wordlists/nl.5000.json URL scheme must be "http" or "https" for CORS request. main @ select.js:591

I've not seen the issue fetching the wordlist before, that's quite odd. I guess the third is a result from that error.

I usually run it with:

```
$ http-server
Starting up http-server, serving ./
Available on:
  http://127.0.0.1:8080
  http://172.27.207.3:8080
Hit CTRL-C to stop the server
[Thu Nov 14 2019 10:32:34 GMT+0100 (CET)] "GET /" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
[Thu Nov 14 2019 10:32:34 GMT+0100 (CET)] "GET /style.css" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
[Thu Nov 14 2019 10:32:34 GMT+0100 (CET)] "GET /layout_generator.js" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
[Thu Nov 14 2019 10:32:34 GMT+0100 (CET)] "GET /lib.js" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
[Thu Nov 14 2019 10:32:34 GMT+0100 (CET)] "GET /select.js" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
[Thu Nov 14 2019 10:32:34 GMT+0100 (CET)] "GET /wordlists/nl.5000.json" "Mozilla/5.0 (X11; Ubuntu; Linux x86_64; rv:70.0) Gecko/20100101 Firefox/70.0"
```

using the [http-server](https://www.npmjs.com/package/http-server) module and that works?

**Comment by MichaelWehar** [comment]
Thank you so much for the quick reply!  :)

I tried the link that you suggested on my desktop computer.  It mostly worked in chrome and firefox on linux, but the crossword boxes were stretched horizontally and the user input didn't seem to work.

Also, running the http-server got it to run on my local computer.

And, I tried your link on my android phone and it worked.  It's really great!

**Comment by MichaelWehar** [comment]
Also, thank you so much for using my crossword layout generator!

Please keep in touch and let me know if there is anything I can help with.  :)

**Comment by hexylena** [comment]
Oh yeah it works horribly on desktop, didn't even bother trying to make it work there since the parents only use mobile phones. Glad you like it!

I've added some attribution to the readme to make it a bit clearer, sorry, didn't fully follow MIT requirements there. I'll find a way to mention it in the 'app' as well.

**Comment by MichaelWehar** [comment]
Thank you so much!  I really appreciate it.

Hope that you have a nice weekend!

**Comment by MichaelWehar** [comment]
Just thought I would let you know that I made a bunch of improvements to the layout generator.  :)
